'use client';

import { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from './ui/dialog';
import { generateProjectDeepDive } from '@/app/actions';
import { Loader2 } from 'lucide-react';
import { ScrollArea } from './ui/scroll-area';

interface CaseStudyModalProps {
  isOpen: boolean;
  onOpenChange: (open: boolean) => void;
  projectId: string;
  projectTitle: string;
}

export default function CaseStudyModal({ isOpen, onOpenChange, projectId, projectTitle }: CaseStudyModalProps) {
  const [deepDive, setDeepDive] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    if (isOpen && !deepDive) {
      setIsLoading(true);
      generateProjectDeepDive(projectId)
        .then((content) => {
          setDeepDive(content);
        })
        .finally(() => {
          setIsLoading(false);
        });
    }
  }, [isOpen, projectId, deepDive]);

  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-3xl h-[80vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="text-2xl">{projectTitle} - AI Deep-Dive</DialogTitle>
          <DialogDescription>
            This technical case study was generated by an AI assistant.
          </DialogDescription>
        </DialogHeader>
        <div className="flex-1 min-h-0">
            <ScrollArea className="h-full pr-6">
            {isLoading ? (
                <div className="flex items-center justify-center h-full">
                <div className="flex flex-col items-center gap-2 text-muted-foreground">
                    <Loader2 className="h-8 w-8 animate-spin text-primary" />
                    <p>Generating deep-dive...</p>
                </div>
                </div>
            ) : (
                <div 
                    className="prose prose-invert prose-sm sm:prose-base max-w-none" 
                    dangerouslySetInnerHTML={{ __html: deepDive.replace(/\n/g, '<br />') }} 
                />
            )}
            </ScrollArea>
        </div>
      </DialogContent>
    </Dialog>
  );
}
